services:
  mysql:
    image: mysql:8.4
    container_name: booking-mysql
    environment:
      MYSQL_DATABASE: booking_server
      MYSQL_USER: booking
      MYSQL_PASSWORD: booking
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "13306:3306" # 로컬에서 이미 돌리고 있는 포트 존재 가능성 때문에 13306으로 사용
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  redis:
    image: redis:7.4-alpine
    container_name: booking-redis
    ports:
      - "16379:6379" #로컬에서 이미 돌리고 있는 포트 존재 가능성 때문에 16379로 사용
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql-data:
  redis-data:
